# Generated by Django 5.2.5 on 2025-11-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ourservice", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="contactfrom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullname", models.CharField(max_length=150)),
                ("email", models.CharField(max_length=150)),
                ("phone", models.CharField(max_length=150)),
                ("message", models.CharField(max_length=250)),
            ],
        ),
    ]
