# Generated by Django 5.2.5 on 2025-11-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contactApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactform",
            name="attachment",
            field=models.FileField(blank=True, null=True, upload_to="uploads/files/"),
        ),
        migrations.AddField(
            model_name="contactform",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="uploads/images/"),
        ),
    ]
