# Generated by Django 5.2.5 on 2025-11-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contactApp", "0002_contactform_attachment_contactform_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ourguards",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("person", models.CharField(max_length=250)),
                ("post", models.CharField(max_length=250)),
                (
                    "img",
                    models.ImageField(
                        blank=True,
                        default=None,
                        max_length=250,
                        null=True,
                        upload_to="ourguards/",
                    ),
                ),
            ],
        ),
    ]
